### ISSUE TITLE
Could not use the XeLatex

### ISSUE THREAD

**Issue by Noietch** [overleaf/overleaf#1055]
I have deployed the overleaf community version on my server However, I can not use the XeLatex to complie the articles.

```
No PDF
This compile didn’t produce a PDF. This can happen if:
There is an unrecoverable LaTeX error. If there are LaTeX errors shown below or in the raw logs, please try to fix them and compile again.
The document environment contains no content. If it’s empty, please add some content and compile again.
This project contains a file called output.pdf. If that file exists, please rename it and compile again.
```

```
====== Overleaf Doctor ======
- Host Information
    - Linux
    - Output of 'lsb_release -a':
            No LSB modules are available.
            Distributor ID:     Ubuntu
            Description:        Ubuntu 20.04 LTS
            Release:    20.04
            Codename:   focal
- Dependencies
    - bash
        - status: present
        - version info: 5.0.17(1)-release
    - docker
        - status: present
        - version info: Docker version 20.10.21, build baeda1f
    - docker-compose
        - status: present
        - version info: docker-compose version 1.25.0, build unknown
    - realpath
        - status: present
        - version info: realpath (GNU coreutils) 8.30
    - perl
        - status: present
        - version info: 5.030000
    - awk
        - status: present
        - version info: GNU Awk 5.0.1, API: 2.0 (GNU MPFR 4.0.2, GNU MP 6.2.0)
    - openssl
        - status: present
        - version info: OpenSSL 1.1.1f  31 Mar 2020
- Docker Daemon
    - status: up
====== Configuration ======
- config/version
    - status: present
    - version: 3.3.0
- config/overleaf.rc
    - status: present
    - values
        - SHARELATEX_DATA_PATH: data/sharelatex
        - SERVER_PRO: false
        - SHARELATEX_LISTEN_IP: 0.0.0.0
        - SHARELATEX_PORT: 5000
        - MONGO_ENABLED: true
        - MONGO_IMAGE: mongo:4.4
        - MONGO_DATA_PATH: data/mongo
        - REDIS_ENABLED: true
        - REDIS_DATA_PATH: data/redis
        - NGINX_ENABLED: false
        - NGINX_CONFIG_PATH: config/nginx/nginx.conf
        - TLS_PRIVATE_KEY_PATH: config/nginx/certs/overleaf_key.pem
        - TLS_CERTIFICATE_PATH: config/nginx/certs/overleaf_certificate.pem
        - NGINX_HTTP_LISTEN_IP: 127.0.1.1
        - NGINX_HTTP_PORT: 80
        - NGINX_TLS_LISTEN_IP: 127.0.1.1
        - TLS_PORT: 443
- config/variables.env
    - status: present
====== Warnings ======
- None, all good
====== End ======
```

**Comment by Musicminion** [comment]
Me too!

The details are as followings
```
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
Latexmk: Changing directory to '/var/lib/sharelatex/data/compiles/636232dd7d1c01007f9fc990-636225487d1c01007f9fc8be/'
Latexmk: applying rule 'xelatex'...
Rule 'xelatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
  main.tex
Rule 'xelatex': The following rules & subrules became out-of-date:
  xelatex
------------
Run number 1 of rule 'xelatex'
------------
------------
Running 'xelatex -no-pdf -synctex=1 -interaction=batchmode -recorder --jobname="output"  "main.tex"'
------------
Latexmk: Getting log file 'output.log'
Latexmk: Errors, in force_mode: so I tried finishing targets
Collected error summary (may duplicate other messages):
  xelatex: Run of rule 'xelatex' gave a non-zero error code
Latexmk: Undoing directory change

```

**Comment by Musicminion** [comment]
OHHHHHHH！
I have solve this problem after struggling for a day！
I tested sharelatex/sharelatex:latest; 3.0;3.1;3.2;3.2.2;2.4.X, none of them worked porpley!
```
# enter the sharelatex container
docker exec -it sharelatex /bin/bash
apt-get update
apt-get install texlive-xetex latex-cjk-all
apt-get install texmaker
```
 
<img width="1488" alt="截屏2022-11-02 21 02 08" src="https://user-images.githubusercontent.com/84625273/199496381-f4ff872c-2ef9-4f81-b85f-6fd4de358d49.png">

**Comment by Musicminion** [comment]
I am sorry for make some mistakes! Maybe you should consider the following way
The root of this problem is there is none `xelatex` engine at all, however, when you install(or update) texlive/2022 for example, `xelatex` is included!
So ,you only need to add your texlive path to your docker system's env $PATH, after that, everything goes well, and you can also use some package.

enter your `overleaf-tool` dir,
```
cd lib
vim docker-compose.base.yml
# nano docker-compose.base.yml, it depends on your likes
```

make changes like these!, add PATH env, don't forget to edit `2022` if you use another version!
```
---
version: '2.2'
services:

    sharelatex:
        restart: always
        image: "${IMAGE}"
        container_name: sharelatex
        volumes:
            - "${SHARELATEX_DATA_PATH}:/var/lib/sharelatex"
        ports:
            - "${SHARELATEX_LISTEN_IP:-127.0.0.1}:${SHARELATEX_PORT:-80}:80"
        environment:
          SHARELATEX_MONGO_URL: "${MONGO_URL}"
          SHARELATEX_REDIS_HOST: "${REDIS_HOST}"
          REDIS_HOST: "${REDIS_HOST}"
          PATH: /usr/local/texlive/2022/bin/x86_64-linux:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        env_file: ../config/variables.env
```

Then, backup your docker, since the following options will delete old container named sharelatex

It's time to come back to your `overleaf-tool`main dir,
```
# Attention! THIS WILL DELETE OLD CONTAINER AND CREATE NEW ONE! 
# Make sure you backup everthings you want to keep
sudo bin/up
```

Enter your docker by
```
sudo docker exec -it sharelatex /bin/bash
tlmgr update --self
tlmgr install scheme-full
```
