### ISSUE TITLE
Biblatex not working due to missing PATH entry

### ISSUE THREAD

**Issue by chschenk** [overleaf/overleaf#1081]
## Steps to Reproduce
1. Upgrade to Overleaf 3.4.0 Comunity Edition via Overleaf toolkit
2. Install packages with "tlmgr install scheme-full"
3. Try to compile a project which uses biblatex (For example the minimal working example from here: https://www.overleaf.com/learn/latex/Bibliography_management_with_biblatex)

## Expected Behaviour
The project should compile normally

## Observed Behaviour
Overleaf produces warnings that the citations are undefined and no bibliography is created

## Context
Trying to compile a project which uses the biblatex package

## Technical Info
The directory `/usr/local/texlive/2022/bin/x86_64-linux/` is missing in the $PATH environment variable.
Because of that latexmk cant find biber, which is used by biblatex and located in that directory.
Also tlmgr produces errors like:
```
running mtxrun --generate ...

tlmgr: mtxrun --generate failed (status -1), output:
```
Because mtxrun is also located under `/usr/local/texlive/2022/bin/x86_64-linux/`.

A quick (and ugly) workaround for this issue is to create a "docker-compose.override.yml" file in the config directory with the following contents:
```
---
version: "2.2"
services:
    sharelatex:
        environment:
                - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/texlive/2022/bin/x86_64-linux
```
## Analysis
I think this problem was introduced in the following commit: https://github.com/overleaf/overleaf/commit/ed67590cc94386eb9735bf1ca27dd147aa423c48
It seems like it isn't enough to call `tlmgr path add` while building the image. Because in this way the correct path is never written to `/etc/container_environment/PATH` which is read by the `/sbin/my_init` script at container startup to setup environment variables.
