### ISSUE TITLE
K8S listen on IPv6

### ISSUE THREAD

**Issue by Korov** [overleaf/overleaf#1170]
## Steps to Reproduce

```
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharelatex
  namespace: korov
  labels:
    app: sharelatex
spec:
  serviceName: sharelatex
  replicas: 1
  selector:
    matchLabels:
      app: sharelatex
  template:
    metadata:
      labels:
        app: sharelatex
    spec:
      containers:
      - name: sharelatex
        image: sharelatex/sharelatex:4.2.1
        ports:
        - containerPort: 80
        env:
        - name: SHARELATEX_APP_NAME
          value: "Overleaf Community Edition"
        - name: SHARELATEX_MONGO_URL
          value: "mongodb://127.0.0.1:27017/sharelatex"
        - name: SHARELATEX_REDIS_HOST
          value: "127.0.0.1"
        - name: ENABLE_CONVERSIONS
          value: "true"
        - name: EMAIL_CONFIRMATION_DISABLED
          value: "true"
        resources:
          limits:
            cpu: "4"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 50Mi

      - name: sharelatex-mongo
        image: bitnami/mongodb:7.0.4
        ports:
        - containerPort: 27017
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MONGODB_REPLICA_SET_MODE
          value: "primary"
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi

      - name: sharelatex-redis
        image: redis:7.2.3-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: sharelatex
  namespace: korov
spec:
  type: NodePort
  selector:
    app: sharelatex
  ports:
  - protocol: TCP
    name: sharelatex
    port: 80
    targetPort: 80
    nodePort: 18050
```

I get this

```bash
root@sharelatex-0:/etc/nginx/sites-enabled# netstat -ant | grep 3026
tcp6       0      0 ::1:3026                :::*                    LISTEN   
root@sharelatex-0:/etc/nginx/sites-enabled# netstat -ant | grep 4000
tcp6       0      0 ::1:4000                :::*                    LISTEN  
```

but the ngnix config is 

```
location / {
		proxy_pass http://127.0.0.1:4000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_read_timeout 10m;
		proxy_send_timeout 10m;
	}

	location /socket.io {
		proxy_pass http://127.0.0.1:3026;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_read_timeout 10m;
		proxy_send_timeout 10m;
	}
```

so the web always show bad gateway

**Comment by Korov** [comment]
I resolved it
```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sharelatex
  namespace: korov
  labels:
    app: sharelatex
spec:
  serviceName: sharelatex
  replicas: 1
  selector:
    matchLabels:
      app: sharelatex
  template:
    metadata:
      labels:
        app: sharelatex
    spec:
      containers:
      - name: sharelatex
        image: sharelatex/sharelatex:4.2.1
        ports:
        - containerPort: 80
        env:
        - name: SHARELATEX_APP_NAME
          value: "Overleaf Community Edition"
        - name: SHARELATEX_MONGO_URL
          value: "mongodb://127.0.0.1:27017/sharelatex"
        - name: SHARELATEX_REDIS_HOST
          value: "127.0.0.1"
        - name: ENABLE_CONVERSIONS
          value: "true"
        - name: EMAIL_CONFIRMATION_DISABLED
          value: "true"
        - name: PUBLIC_URL
          value: "http://service.korov.org:3000"
        - name: SHARELATEX_EMAIL_SMTP_HOST
          value: "0.0.0.0"
        - name: WEB_HOST
          value: "0.0.0.0"
        - name: LISTEN_ADDRESS
          value: "0.0.0.0"
        - name: WEB_API_HOST
          value: "0.0.0.0"
        - name: DOCUPDATER_HOST
          value: "0.0.0.0"
        - name: SPELLING_HOST
          value: "0.0.0.0"
        - name: DOCSTORE_HOST
          value: "0.0.0.0"
        - name: CHAT_HOST
          value: "0.0.0.0"
        - name: FILESTORE_HOST
          value: "0.0.0.0"
        - name: CLSI_HOST
          value: "0.0.0.0"
        - name: PROJECT_HISTORY_HOST
          value: "0.0.0.0"
        - name: REALTIME_HOST
          value: "0.0.0.0"
        - name: CONTACTS_HOST
          value: "0.0.0.0"
        - name: NOTIFICATIONS_HOST
          value: "0.0.0.0"
        - name: WEBPACK_HOST
          value: "0.0.0.0"
        - name: V1_HISTORY_HOST
          value: "0.0.0.0"
        resources:
          limits:
            cpu: "4"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 50Mi

      - name: sharelatex-mongo
        image: bitnami/mongodb:7.0.4
        ports:
        - containerPort: 27017
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MONGODB_REPLICA_SET_MODE
          value: "primary"
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 50Mi

      - name: sharelatex-redis
        image: redis:7.2.3-alpine
        command: ["redis-server"]
        args: ["--requirepass", ""]
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: sharelatex
  namespace: korov
spec:
  type: NodePort
  selector:
    app: sharelatex
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 18050
```
