### ISSUE TITLE
MongoDB not saved user/password

### ISSUE THREAD

**Issue by ignisVeneficus** [overleaf/overleaf#1213]
I set up a overleaf doker compose based on sharelatex/sharelatex:3.5.13
(I used that because this is the version which is started without any problem, with the mongoDB)
( i extented the original with a "tlmgr install scheme-full" command)
```
  sharelatex:
    restart: unless-stopped
    build:
      context: ${SHARELATEX_PATH}
      dockerfile: Dockerfile
    container_name: sharelatex
    depends_on:
      sharelatexmongo:
        condition: service_healthy
      sharelatexredis:
        condition: service_started
    links:
      - sharelatexmongo
      - sharelatexredis
    volumes:
      - ${SHARELATEX_PATH}/data:/var/lib/sharelatex
    environment:
      SHARELATEX_APP_NAME: Overleaf
      SHARELATEX_MONGO_URL: mongodb://sharelatexmongo/sharelatex 
      SHARELATEX_REDIS_HOST: sharelatexredis
      REDIS_HOST: sharelatexredis
      ENABLED_LINKED_FILE_TYPES: 'url,project_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var
      SHARELATEX_BEHIND_PROXY: 'true'
      SHARELATEX_SECURE_COOKIE: 'true'
      SHARELATEX_SITE_LANGUAGE: 'en'
  sharelatexmongo:
    restart: unless-stopped
    image: bitnami/mongodb:4.4
    container_name: sharelatexmongo
    expose:
      - 27017
    volumes:
      - ${SHARELATEX_DB_PATH}/data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
  sharelatexredis:
    restart: unless-stopped
    image: redis:6.2
    container_name: sharelatexredis
    expose:
      - 6379
    volumes:
      - ${SHARELATEX_REDIS_PATH}/data:/data

```
(env variables is correct stetted, double checked)

## Expected Behaviour
After create a admin user, and restart the mongoDB I excepted, the user is there and I can log into

## Observed Behaviour
After the mongoDB restart the app dont let in as admin, need to create an admin user again.
The mongoDB data directory is empty.
Not found any mongoDB error in the docker log

I think there is some configuration error, but i dont found it.
Thanx
