### ISSUE TITLE
Sorry, something went wrong and your project could not be compiled. Please try again in a few moments.

### ISSUE THREAD

**Issue by kuangmeng** [overleaf/overleaf#1337]
Sorry, something went wrong and your project could not be compiled. Please try again in a few moments.

self-hosted Overleaf community 1.45

**Comment by kevin-hwang-overleaf** [comment]
@kuangmeng So we can investigate, are you able to provide the actual version number of Community Edition you are using? It would also be helpful to have details of your deployment (toolkit or docker compose). If you're able to provide the /var/log/overleaf/web.log from the time you experienced the compile error, that would be helpful.

**Comment by HighwayStar** [comment]
I have this issue too, with large project that require about 12 minutes to compile in cli on same server, but something went wrong error shown after about 10 minutes.

web log produced when something went wrong message show is 

```
web           | {"name":"web","hostname":"48922825788a","pid":204,"level":50,"err":{"message":"failed to make request to CLSI","name":"OError","stack":"OError: failed to make request to CLSI
    at _postToClsi (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:496:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _sendBuiltRequest (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:180:38)
    at async sendRequestOnce (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:91:10)
    at async Object.sendRequest (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:57:16)
    at async compile (/overleaf/services/web/app/src/Features/Compile/CompileManager.js:81:7)
    at async Object.<anonymous> (/overleaf/services/web/app/src/Features/Compile/CompileManager.js:21:14)
caused by:
    FetchError: request to http://127.0.0.1:3013/project/680cd09261b765e03da70a22/user/54812253dd559da71ee5229d/compile?compileBackendClass=n2d&compileGroup=standard failed, reason: socket hang up
        at ClientRequest.<anonymous> (/overleaf/node_modules/node-fetch/lib/index.js:1501:11)
        at ClientRequest.emit (node:events:524:28)
        at ClientRequest.emit (node:domain:489:12)
        at emitErrorEvent (node:_http_client:101:11)
        at Socket.socketOnEnd (node:_http_client:528:5)
        at Socket.emit (node:events:536:35)
        at Socket.emit (node:domain:489:12)
        at endReadableNT (node:internal/streams/readable:1698:12)
        at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    TaggedError: request to http://127.0.0.1:3013/project/680cd09261b765e03da70a22/user/54812253dd559da71ee5229d/compile?compileBackendClass=n2d&compileGroup=standard failed, reason: socket hang up
        at performRequest (/overleaf/libraries/fetch-utils/index.js:224:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async fetchStringWithResponse (/overleaf/libraries/fetch-utils/index.js:133:20)
        at async _makeRequest (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:282:28)
        at async _postToClsi (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:463:36)
        at async _sendBuiltRequest (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:180:38)
        at async sendRequestOnce (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:91:10)
        at async Object.sendRequest (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:57:16)
        at async compile (/overleaf/services/web/app/src/Features/Compile/CompileManager.js:81:7)
        at async Object.<anonymous> (/overleaf/services/web/app/src/Features/Compile/CompileManager.js:21:14)
    TaggedError: error making request to CLSI
        at _makeRequest (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:284:18)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async _postToClsi (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:463:36)
        at async _sendBuiltRequest (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:180:38)
        at async sendRequestOnce (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:91:10)
        at async Object.sendRequest (/overleaf/services/web/app/src/Features/Compile/ClsiManager.js:57:16)
        at async compile (/overleaf/services/web/app/src/Features/Compile/CompileManager.js:81:7)
        at async Object.<anonymous> (/overleaf/services/web/app/src/Features/Compile/CompileManager.js:21:14)","info":{"url":"http://127.0.0.1:3013/project/680cd09261b765e03da70a22/user/54812253dd559da71ee5229d/compile?compileBackendClass=n2d&compileGroup=standard","method":"POST","projectId":"680cd09261b765e03da70a22","userId":"54812253dd559da71ee5229d","compileOptions":{"compiler":"xelatex","timeout":100,"imageName":"texlive/texlive:latest-full","draft":false,"stopOnFirstError"
```

**Comment by csmharis1** [comment]
I have the same problem. Tried different solutions but nothing works. Any lead

**Comment by RPadial** [comment]
same problem:
nginx enabled 

services:
    sharelatex:
        restart: always
        # Server Pro users:
        # image: quay.io/sharelatex/sharelatex-pro
        image: sharelatex/sharelatex
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        # ports:
        #     - 80:80
        stop_grace_period: 60s
        volumes:
            - /home/common/overleaf/sharelatex/sharelatex_data:/var/lib/overleaf
            ########################################################################
            ####  Server Pro: Uncomment the following line to mount the docker  ####
            ####             socket, required for Sibling Containers to work    ####
            ########################################################################
            # - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - default
        environment:

            OVERLEAF_APP_NAME: Overleaf Community Edition

            OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex

            # Same property, unfortunately with different names in
            # different locations
            OVERLEAF_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'true'
            

            # Set for SSL via nginx-proxy
            # VIRTUAL_HOST: 103.112.212.22
            VIRTUAL_HOST: myurl.com

            OVERLEAF_SITE_URL: https://myurl.com
            OVERLEAF_NAV_TITLE:  Overleaf CE
            # OVERLEAF_HEADER_IMAGE_URL: http://example.com/mylogo.png
            # OVERLEAF_ADMIN_EMAIL: support@it.com

            # OVERLEAF_LEFT_FOOTER: '[{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            # OVERLEAF_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'

            # OVERLEAF_EMAIL_FROM_ADDRESS: "hello@example.com"

            # OVERLEAF_EMAIL_AWS_SES_ACCESS_KEY_ID:
            # OVERLEAF_EMAIL_AWS_SES_SECRET_KEY:

            # OVERLEAF_EMAIL_SMTP_HOST: smtp.example.com
            # OVERLEAF_EMAIL_SMTP_PORT: 587
            # OVERLEAF_EMAIL_SMTP_SECURE: false
            # OVERLEAF_EMAIL_SMTP_USER:
            # OVERLEAF_EMAIL_SMTP_PASS:
            # OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            # OVERLEAF_EMAIL_SMTP_IGNORE_TLS: false
            # OVERLEAF_EMAIL_SMTP_NAME: '127.0.0.1'
            # OVERLEAF_EMAIL_SMTP_LOGGER: true
            # OVERLEAF_CUSTOM_EMAIL_FOOTER: "This system is run by department x"

            # ENABLE_CRON_RESOURCE_DELETION: true

            ################
            ## Server Pro ##
            ################

            ## The Community Edition is intended for use in environments where all users are trusted and is not appropriate for
            ## scenarios where isolation of users is required. Sandboxed Compiles are not available in the Community Edition,
            ## so the following environment variables must be commented out to avoid compile issues.
            ##
            ## Sandboxed Compiles: https://docs.overleaf.com/on-premises/configuration/overleaf-toolkit/server-pro-only-configuration/sandboxed-compiles
            SANDBOXED_COMPILES: 'true'
            ### Bind-mount source for /var/lib/overleaf/data/compiles inside the container.
            SANDBOXED_COMPILES_HOST_DIR_COMPILES: '/home/user/sharelatex_data/data/compiles'
            ### Bind-mount source for /var/lib/overleaf/data/output inside the container.
            SANDBOXED_COMPILES_HOST_DIR_OUTPUT: '/home/user/sharelatex_data/data/output'
            ### Backwards compatibility (before Server Pro 5.5)
            DOCKER_RUNNER: 'true'
            SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'

            ## Works with test LDAP server shown at bottom of docker compose
            # OVERLEAF_LDAP_URL: 'ldap://ldap:389'
            # OVERLEAF_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
            # OVERLEAF_LDAP_SEARCH_FILTER: '(uid={{username}})'
            # OVERLEAF_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
            # OVERLEAF_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
            # OVERLEAF_LDAP_EMAIL_ATT: 'mail'
            # OVERLEAF_LDAP_NAME_ATT: 'cn'
            # OVERLEAF_LDAP_LAST_NAME_ATT: 'sn'
            # OVERLEAF_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'

            # OVERLEAF_TEMPLATES_USER_ID: "578773160210479700917ee5"
            # OVERLEAF_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"All Templates","url":"/templates/all"}]'


            # OVERLEAF_PROXY_LEARN: "true"

    mongo:
        restart: always
        image: mongo:6.0
        container_name: mongo
        command: '--replSet overleaf'
        volumes:
            - /home/common/overleaf/mongo/mongo_data:/data/db
            - /home/common/overleaf/mongo/bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
        environment:
          MONGO_INITDB_DATABASE: sharelatex
        # extra_hosts:
        #   # Required when using the automatic database setup for initializing the replica set.
        #   # This override is not needed when running the setup after starting up mongo.
        #   - mongo:127.0.0.1
          # - mongo:10.19.0.1
        healthcheck:
            test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
        networks:
            - default

    redis:
        restart: always
        image: redis:6.2
        container_name: redis
        volumes:
            - /home/common/overleaf/redis/redis_data:/data
        networks:
            - default

# PROBLEM: sharelatex cannote reach to mong
# FIX: https://github.com/overleaf/overleaf/issues/1332
# docker exec -it mongo mongosh --eval "rs.initiate({
#   _id: 'overleaf',
#   members: [
#     { _id: 0, host: 'mongo:27017' }
#   ]
# })"

    # ldap:
    #    restart: always
    #    image: rroemhild/test-openldap
    #    container_name: ldap

    # See https://github.com/jwilder/nginx-proxy for documentation on how to configure the nginx-proxy container,
    # and https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx for an example of some recommended
    # settings. We recommend using a properly managed nginx instance outside of the Overleaf Server Pro setup,
    # but the example here can be used if you'd prefer to run everything with docker-compose

    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
          # - "8086:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /home/common/overleaf/ngx/certs:/etc/nginx/certs
        networks:
          - default
    
networks:
  default:
    ipam: 
      config:
        - subnet: 10.19.0.0/16
          gateway: 10.19.0.1

**Comment by RPadial** [comment]
> same problem: nginx enabled
> 
> services: sharelatex: restart: always # Server Pro users: # image: quay.io/sharelatex/sharelatex-pro image: sharelatex/sharelatex container_name: sharelatex depends_on: mongo: condition: service_healthy redis: condition: service_started # ports: # - 80:80 stop_grace_period: 60s volumes: - /home/common/overleaf/sharelatex/sharelatex_data:/var/lib/overleaf ######################################################################## #### Server Pro: Uncomment the following line to mount the docker #### #### socket, required for Sibling Containers to work #### ######################################################################## # - /var/run/docker.sock:/var/run/docker.sock networks: - default environment:
> 
> ```
>         OVERLEAF_APP_NAME: Overleaf Community Edition
> 
>         OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex
> 
>         # Same property, unfortunately with different names in
>         # different locations
>         OVERLEAF_REDIS_HOST: redis
>         REDIS_HOST: redis
> 
>         ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'
> 
>         # Enables Thumbnail generation using ImageMagick
>         ENABLE_CONVERSIONS: 'true'
> 
>         # Disables email confirmation requirement
>         EMAIL_CONFIRMATION_DISABLED: 'true'
>         
> 
>         # Set for SSL via nginx-proxy
>         # VIRTUAL_HOST: 103.112.212.22
>         VIRTUAL_HOST: myurl.com
> 
>         OVERLEAF_SITE_URL: https://myurl.com
>         OVERLEAF_NAV_TITLE:  Overleaf CE
>         # OVERLEAF_HEADER_IMAGE_URL: http://example.com/mylogo.png
>         # OVERLEAF_ADMIN_EMAIL: support@it.com
> 
>         # OVERLEAF_LEFT_FOOTER: '[{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
>         # OVERLEAF_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'
> 
>         # OVERLEAF_EMAIL_FROM_ADDRESS: "hello@example.com"
> 
>         # OVERLEAF_EMAIL_AWS_SES_ACCESS_KEY_ID:
>         # OVERLEAF_EMAIL_AWS_SES_SECRET_KEY:
> 
>         # OVERLEAF_EMAIL_SMTP_HOST: smtp.example.com
>         # OVERLEAF_EMAIL_SMTP_PORT: 587
>         # OVERLEAF_EMAIL_SMTP_SECURE: false
>         # OVERLEAF_EMAIL_SMTP_USER:
>         # OVERLEAF_EMAIL_SMTP_PASS:
>         # OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
>         # OVERLEAF_EMAIL_SMTP_IGNORE_TLS: false
>         # OVERLEAF_EMAIL_SMTP_NAME: '127.0.0.1'
>         # OVERLEAF_EMAIL_SMTP_LOGGER: true
>         # OVERLEAF_CUSTOM_EMAIL_FOOTER: "This system is run by department x"
> 
>         # ENABLE_CRON_RESOURCE_DELETION: true
> 
>         ################
>         ## Server Pro ##
>         ################
> 
>         ## The Community Edition is intended for use in environments where all users are trusted and is not appropriate for
>         ## scenarios where isolation of users is required. Sandboxed Compiles are not available in the Community Edition,
>         ## so the following environment variables must be commented out to avoid compile issues.
>         ##
>         ## Sandboxed Compiles: https://docs.overleaf.com/on-premises/configuration/overleaf-toolkit/server-pro-only-configuration/sandboxed-compiles
>         SANDBOXED_COMPILES: 'true'
>         ### Bind-mount source for /var/lib/overleaf/data/compiles inside the container.
>         SANDBOXED_COMPILES_HOST_DIR_COMPILES: '/home/user/sharelatex_data/data/compiles'
>         ### Bind-mount source for /var/lib/overleaf/data/output inside the container.
>         SANDBOXED_COMPILES_HOST_DIR_OUTPUT: '/home/user/sharelatex_data/data/output'
>         ### Backwards compatibility (before Server Pro 5.5)
>         DOCKER_RUNNER: 'true'
>         SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
> 
>         ## Works with test LDAP server shown at bottom of docker compose
>         # OVERLEAF_LDAP_URL: 'ldap://ldap:389'
>         # OVERLEAF_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
>         # OVERLEAF_LDAP_SEARCH_FILTER: '(uid={{username}})'
>         # OVERLEAF_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
>         # OVERLEAF_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
>         # OVERLEAF_LDAP_EMAIL_ATT: 'mail'
>         # OVERLEAF_LDAP_NAME_ATT: 'cn'
>         # OVERLEAF_LDAP_LAST_NAME_ATT: 'sn'
>         # OVERLEAF_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'
> 
>         # OVERLEAF_TEMPLATES_USER_ID: "578773160210479700917ee5"
>         # OVERLEAF_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"All Templates","url":"/templates/all"}]'
> 
> 
>         # OVERLEAF_PROXY_LEARN: "true"
> 
> mongo:
>     restart: always
>     image: mongo:6.0
>     container_name: mongo
>     command: '--replSet overleaf'
>     volumes:
>         - /home/common/overleaf/mongo/mongo_data:/data/db
>         - /home/common/overleaf/mongo/bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
>     environment:
>       MONGO_INITDB_DATABASE: sharelatex
>     # extra_hosts:
>     #   # Required when using the automatic database setup for initializing the replica set.
>     #   # This override is not needed when running the setup after starting up mongo.
>     #   - mongo:127.0.0.1
>       # - mongo:10.19.0.1
>     healthcheck:
>         test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
>         interval: 10s
>         timeout: 10s
>         retries: 5
>     networks:
>         - default
> 
> redis:
>     restart: always
>     image: redis:6.2
>     container_name: redis
>     volumes:
>         - /home/common/overleaf/redis/redis_data:/data
>     networks:
>         - default
> ```
> 
> # PROBLEM: sharelatex cannote reach to mong
> # FIX: [#1332](https://github.com/overleaf/overleaf/issues/1332)
> # docker exec -it mongo mongosh --eval "rs.initiate({
> # _id: 'overleaf',
> # members: [
> # { _id: 0, host: 'mongo:27017' }
> # ]
> # })"
> 
> ```
> # ldap:
> #    restart: always
> #    image: rroemhild/test-openldap
> #    container_name: ldap
> 
> # See https://github.com/jwilder/nginx-proxy for documentation on how to configure the nginx-proxy container,
> # and https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx for an example of some recommended
> # settings. We recommend using a properly managed nginx instance outside of the Overleaf Server Pro setup,
> # but the example here can be used if you'd prefer to run everything with docker-compose
> 
> nginx-proxy:
>     image: jwilder/nginx-proxy
>     container_name: nginx-proxy
>     ports:
>       # - "8086:80"
>       - "443:443"
>     volumes:
>       - /var/run/docker.sock:/tmp/docker.sock:ro
>       - /home/common/overleaf/ngx/certs:/etc/nginx/certs
>     networks:
>       - default
> ```
> 
> networks: default: ipam: config: - subnet: 10.19.0.0/16 gateway: 10.19.0.1

Fixed by removing SANDBOXED env variables as docker compose template explains

**Comment by mlevans0** [comment]
I'm glad you were able to resolve the issue @RPadial. @csmharis1 did you manage to resolve the issue?

**Comment by PramSin** [comment]
@mlevans0 Hello, I also met this issue when compiling large pdf files, and below is my docker.yaml.
<details><summary>Details</summary>
<p>

```yaml
version: "3.9"

volumes:
  data:
  log:
  dist:
  fonts:
  mongo_data:
  mongo_conf:
  redis_data:

networks:
  default:
    name: kong_default
    external: true

services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex:5
    container_name: overleaf_sharelatex
    volumes:
      - data:/var/lib/overleaf
      - log:/var/log/overleaf
      - dist:/usr/local/texlive/2025/texmf-dist
      - fonts:/usr/share/fonts
    environment:
      OVERLEAF_APP_NAME: ${OVERLEAF_APP_NAME}
      OVERLEAF_SITE_URL: ${OVERLEAF_SITE_URL}
      OVERLEAF_ADMIN_EMAIL: ${OVERLEAF_ADMIN_EMAIL}
      OVERLEAF_MONGO_URL: mongodb://mongo:27017/overleaf
      OVERLEAF_REDIS_HOST: redis
      V1_HISTORY_URL: http://sharelatex:3100/api
      ENABLED_LINKED_FILE_TYPES: project_file,project_output_file
      ENABLE_CONVERSIONS: true
      EMAIL_CONFIRMATION_DISABLED: true
      OVERLEAF_EMAIL_SMTP_HOST: ${OVERLEAF_EMAIL_SMTP_HOST}
      OVERLEAF_EMAIL_SMTP_PORT: ${OVERLEAF_EMAIL_SMTP_PORT}
      OVERLEAF_EMAIL_SMTP_USER: ${OVERLEAF_EMAIL_SMTP_USER}
      OVERLEAF_EMAIL_SMTP_PASS: ${OVERLEAF_EMAIL_SMTP_PASS}
      OVERLEAF_EMAIL_SMTP_NAME: ${OVERLEAF_EMAIL_SMTP_NAME}
      OVERLEAF_CUSTOM_EMAIL_FOOTER: ${OVERLEAF_CUSTOM_EMAIL_FOOTER}
      OVERLEAF_ALLOW_PUBLIC_ACCESS: true
      OVERLEAF_ALLOW_ANONYMOUS_READ_AND_WRITE_SHARING: true
    stop_grace_period: 60s
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started

  mongo:
    restart: always
    image: mongo:6.0
    container_name: overleaf_mongo
    volumes:
      - mongo_data:/data/db
      - mongo_conf:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: overleaf
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    command:
      - --replSet
      - overleaf

  mongo-init:
    restart: on-failure:5
    image: mongo:6.0
    container_name: overleaf_mongo_init
    depends_on:
      - mongo
    command:
      - mongosh
      - mongodb://mongo:27017/overleaf
      - --eval
      - 'db.isMaster().primary || rs.initiate({ _id: "overleaf", members: [ { _id: 0, host: "mongo:27017" } ] })'

  redis:
    restart: always
    image: redis:6.2
    volumes:
        - redis_data:/data
    container_name: overleaf_redis
    command: redis-server --appendonly yes
```

</p>
</details> 

And there's no `sandbox` envs in it at all, but I still encountered this error.

<img width="988" height="292" alt="Image" src="https://github.com/user-attachments/assets/0f1d6bcd-6b26-44bf-bed5-57d6cb72be88" />

Please reply me if any other log files needed. And I really want to solve this, many thanks!
