### ISSUE TITLE
Upgrading from 5.3.3 to 5.4 fails database mirgration

### ISSUE THREAD

**Issue by realcatgirly** [overleaf/overleaf#1342]
Hi, 

after upgrading to 5.4 my instance wouldn't start anymore. Redis and Mongo were happy, but sharelatex was caught in a restart loop due to failing migrations. Reverting to 5.3.3 works

Logs:

```
sharelatex        | Target migrations:
sharelatex        |     20250115110745_oauth_user_id_index_no_partial
sharelatex        |     20250116090001_deletedUsers_non_expired_index
sharelatex        |     20250126195914_update_deleterData.deletedAt_index
sharelatex        |     20250130104049_create_dropboxEntities_userId_projectId_index
sharelatex        |     20250205145327_drop_rooms_projectId_index
sharelatex        |     20250206103037_create_rooms_projectId_threadId_index
sharelatex        |     20250320161029_update_inactive_project_index
sharelatex        |     20250321092555_add_deleted_to_project_id_in_s3_index
sharelatex        |     20250321112055_create_deletedUsers_email_indexes
sharelatex        |     20250321135735_add_email_to_emails_reversed_hostname_index
sharelatex        | Migrate "20250115110745_oauth_user_id_index_no_partial"
sharelatex        | MongoServerError: Error during migrate "20250115110745_oauth_user_id_index_no_partial": An equivalent index already exists with a different name and options. Requested index: { v: 2, key: { user_id: 1 }, name: "user_id_1", background: true }, existing index: { v: 2, key: { user_id: 1 }, name: "pat_user_id_1", partialFilterExpression: { type: "pat" }, background: true }
sharelatex        |     at Connection.sendCommand (/overleaf/node_modules/mongodb/lib/cmap/connection.js:296:27)
sharelatex        |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
sharelatex        |     at async Connection.command (/overleaf/node_modules/mongodb/lib/cmap/connection.js:323:26)
sharelatex        |     at async Server.command (/overleaf/node_modules/mongodb/lib/sdam/server.js:170:29)
sharelatex        |     at async CreateIndexesOperation.executeCommand (/overleaf/node_modules/mongodb/lib/operations/command.js:76:16)
sharelatex        |     at async CreateIndexesOperation.execute (/overleaf/node_modules/mongodb/lib/operations/indexes.js:122:9)
sharelatex        |     at async tryOperation (/overleaf/node_modules/mongodb/lib/operations/execute_operation.js:203:20)
sharelatex        |     at async executeOperation (/overleaf/node_modules/mongodb/lib/operations/execute_operation.js:73:16)
sharelatex        |     at async Collection.createIndex (/overleaf/node_modules/mongodb/lib/collection.js:329:25)
sharelatex        |     at async Promise.all (index 0)
mongo-sharelatex  | {"t":{"$date":"2025-04-29T07:22:36.813+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn13","msg":"Connection ended","attr":{"remote":"172.25.0.4:56748","uuid":"b215d616-98fa-4c7b-b48b-4a21459d16be","connectionId":13,"connectionCount":7}}
mongo-sharelatex  | {"t":{"$date":"2025-04-29T07:22:36.813+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn14","msg":"Connection ended","attr":{"remote":"172.25.0.4:56758","uuid":"95c5df6a-6365-4ba7-9d59-5061d96feafc","connectionId":14,"connectionCount":5}}
mongo-sharelatex  | {"t":{"$date":"2025-04-29T07:22:36.813+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn15","msg":"Connection ended","attr":{"remote":"172.25.0.4:56772","uuid":"46a9b5d1-3d73-401e-a812-a13e44b86a23","connectionId":15,"connectionCount":6}}
mongo-sharelatex  | {"t":{"$date":"2025-04-29T07:22:36.813+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn16","msg":"Connection ended","attr":{"remote":"172.25.0.4:56784","uuid":"0cdd89bf-77bc-4a60-85e5-53a329e06e42","connectionId":16,"connectionCount":4}}
sharelatex        | npm error Lifecycle script `migrations` failed with error:
sharelatex        | npm error code 1
sharelatex        | npm error path /overleaf/services/web
sharelatex        | npm error workspace @overleaf/web
sharelatex        | npm error location /overleaf/services/web
sharelatex        | npm error command failed
sharelatex        | npm error command sh -c MONGO_SOCKET_TIMEOUT=0 east --es-modules migrate -t server-ce
sharelatex        | npm notice
sharelatex        | npm notice New major version of npm available! 10.8.2 -> 11.3.0
sharelatex        | npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.3.0
sharelatex        | npm notice To update run: npm install -g npm@11.3.0
sharelatex        | npm notice
sharelatex        | *** /etc/my_init.d/900_run_web_migrations.sh failed with status 1
sharelatex        | 
sharelatex        | *** Killing all processes...
sharelatex        | Apr 29 07:22:36 53b549dc0095 syslog-ng[80]: syslog-ng shutting down; version='4.3.1'
sharelatex exited with code 0
```

`docker-compose.yml`:
```
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex:5.4
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        ports:
            - 127.0.0.1:8010:80
        links:
            - mongo
            - redis
        stop_grace_period: 60s
        volumes:
            - ./overleaf_data:/var/lib/overleaf
            - ./texlive:/usr/local/texlive

        environment:

            OVERLEAF_APP_NAME: Overleaf Community Edition

            OVERLEAF_MONGO_URL: mongodb://mongo/sharelatex

            # Same property, unfortunately with different names in
            # different locations
            OVERLEAF_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: 'project_file,project_output_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'false'

            # temporary fix for LuaLaTex compiles
            # see https://github.com/overleaf/overleaf/issues/695
            TEXMFVAR: /var/lib/overleaf/tmp/texmf-var

            OVERLEAF_SITE_URL: https://********
            OVERLEAF_NAV_TITLE: ********
            # OVERLEAF_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            OVERLEAF_RIGHT_FOOTER: '[{"text": "********"} ]'

            OVERLEAF_BEHIND_PROXY: 'true'
            OVERLEAF_SECURE_COOKIE: 'true'

            OVERLEAF_ADMIN_EMAIL: ********
            OVERLEAF_EMAIL_FROM_ADDRESS: "********"
            OVERLEAF_EMAIL_SMTP_HOST: ********
            OVERLEAF_EMAIL_SMTP_PORT: 465
            OVERLEAF_EMAIL_SMTP_SECURE: true
            OVERLEAF_EMAIL_SMTP_USER: ********
            OVERLEAF_EMAIL_SMTP_PASS: '********'
            OVERLEAF_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            OVERLEAF_EMAIL_SMTP_IGNORE_TLS: false
            # OVERLEAF_EMAIL_SMTP_NAME: '127.0.0.1'
            OVERLEAF_EMAIL_SMTP_LOGGER: true
            OVERLEAF_CUSTOM_EMAIL_FOOTER: "********"

            ENABLE_CRON_RESOURCE_DELETION: true

    mongo:
        restart: always
        image: mongo:5.0
        container_name: mongo-sharelatex
        expose:
            - 27017
        volumes:
            - ./mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
        command: "--replSet overleaf"

    redis:
        restart: always
        image: redis:6.2
        container_name: redis-sharelatex
        expose:
            - 6379
        volumes:
            - ./redis_data:/data
```
