### ISSUE TITLE
Unable to start, ? non local database issue

### ISSUE THREAD

**Issue by zeigerpuppy** [overleaf/overleaf#157]
I am attempting to install sharelatex on a debian (sid) server.
I use a separate database server which may be causing issues.
grunt check --force runs without errors (apart from warning about no local redis server, but I tried with a local redis server and got the same error)

my localserver is sharelatex.server and the database server is on 10.0.1.10

I have made sure that connections work but I think my mysql settings are incorrect.  I couldn't find any specifics on how to edit them, so tried putting in a "host" variable

I get the following errors starting:

```
grunt run
Running "concurrent:all" (concurrent) task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task
Running "bunyan" task

Running "execute:web" (execute) task
-> executing /opt/sharelatex/web/app.js
Running "bunyan" task
Running "bunyan" task

Running "execute:document-updater" (execute) task
-> executing /opt/sharelatex/document-updater/app.js

Running "execute:filestore" (execute) task
-> executing /opt/sharelatex/filestore/app.js

Running "execute:clsi" (execute) task
-> executing /opt/sharelatex/clsi/app.js

Running "execute:track-changes" (execute) task
-> executing /opt/sharelatex/track-changes/app.js

Running "execute:docstore" (execute) task
-> executing /opt/sharelatex/docstore/app.js
[2014-07-30T07:42:20.100Z]  INFO: filestore/4323 on sharelatex.server: Loading backend (backend=fs)
connect.multipart() will be removed in connect 3.0
visit https://github.com/senchalabs/connect/wiki/Connect-3.0 for alternatives
connect.limit() will be removed in connect 3.0
Development Enviroment
connections property is deprecated. Use getConnections() method
{"name":"filestore","hostname":"sharelatex.server","pid":4323,"level":30,"err":{"message":"listen EADDRINUSE","name":"Error","stack":"Error: listen EADDRINUSE\n    at errnoException (net.js:904:11)\n    at Server._listen2 (net.js:1042:14)\n    at listen (net.js:1064:10)\n    at net.js:1146:9\n    at asyncCallback (dns.js:68:16)\n    at Object.onanswer [as oncomplete] (dns.js:121:9)","code":"EADDRINUSE","errno":"EADDRINUSE","syscall":"listen","domainEmitter":{"domain":{"domain":null,"_events":{},"_maxListeners":10,"members":[]},"_events":{},"_maxListeners":10,"_connections":0,"connections":0,"_handle":null,"_usingSlaves":false,"_slaves":[],"allowHalfOpen":true,"httpAllowHalfOpen":false,"timeout":120000},"domain":"[Circular]","domainThrown":false},"msg":"top level uncaught exception","time":"2014-07-30T07:42:20.944Z","v":0}

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:904:11)
    at Server._listen2 (net.js:1042:14)
    at listen (net.js:1064:10)
    at net.js:1146:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)
Warning: -> error 8 /opt/sharelatex/docstore/app.js (2401ms) Use --force to continue.

Aborted due to warnings.
    Warning:  Use --force to continue.

        Aborted due to warnings. 
```

Here is my database config settings:

```
# Databases
        # ---------
        mongo:
                url : 'mongodb://sharelatex:password@10.0.1.10/sharelatex

        redis:
                web:
                        host: "10.0.1.10"
                        port: "6379"
                        password: ""

                api:
                        host: "10.0.1.10"
                        port: "6379"
                        password: ""

                fairy:
                        host: "10.0.1.10"
                        port: "6379"
                        password: ""

        mysql:
                clsi:
                        host: "10.0.1.10"
                        database: "sharelatex"
                        username: "sharelatex"
                        password: "password"
                        dialect: "sqlite"
                        storage: Path.resolve(__dirname + "/../db.sqlite")
```
