### ISSUE TITLE
login no longer works

### ISSUE THREAD

**Issue by zeigerpuppy** [overleaf/overleaf#162]
Strangely, my installation of sharelatex no longer accepts logins, users that had a project open can still access it but any new logins are rejected, with the error: 
Something went wrong talking to the server :(. Please try again. 

I can't think of anything I have changed that would affect the sharelatex install.
I have tried restarting sharelatex (actually it left quite a few node processes running, so I killed them too).  I have also checked that the redis server, mongodb and mariadb are running properly.

The structure of my install is fairly standard apart from the fact that I am running the databases on a separate server (but this has worked fine up until this point).

The logs show the following when a login attempt is made:

```
[2014-08-14T01:46:28.816Z] ERROR: web-sharelatex/4890 on sharelatex.server: error passed to top level next middlewear (url=/login, method=POST)
    Error: Forbidden
        at Object.exports.error (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/utils.js:62:13)
        at /opt/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/csrf.js:55:41
        at Object.handle (/opt/sharelatex/web/app/js/infrastructure/Server.js:108:14)
        at next (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.handle (/opt/sharelatex/web/app/js/infrastructure/Server.js:98:14)
        at next (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.session [as handle] (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/session.js:301:7)
        at next (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at Object.cookieParser [as handle] (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/cookieParser.js:60:5)
        at next (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/proto.js:190:15)
        at multipart (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/multipart.js:60:27)
        at /opt/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:57:9
        at urlencoded (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/urlencoded.js:48:27)
        at /opt/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:55:7
        at IncomingMessage.<anonymous> (/opt/sharelatex/web/node_modules/express/node_modules/connect/lib/middleware/json.js:82:9)
        at IncomingMessage.emit (events.js:92:17)
        at _stream_readable.js:929:16
        at process._tickCallback (node.js:419:13)
```

My database settings (*previously working fine) are below (ip address of database server replaced by  "database_server" for security)

```
       mongo:
                url : 'mongodb://sharelatex:password@database_server/sharelatex'

        redis:
                web:
                        host: "database_server"
                        port: "6379"
                        password: ""

                api:
                        host: "database_server"
                        port: "6379"
                        password: ""

                fairy:
                        host: "database_server"
                        port: "6379"
                        password: ""

        mysql:
                clsi:
                        host: "database_server"
                        database: "sharelatex"
                        username: "sharelatex"
                        password: "password"
                        dialect: "sqlite"
                        storage: Path.resolve(__dirname + "/../db.sqlite")
```
