### ISSUE TITLE
Crash after adding Amazon s3 Credentials

### ISSUE THREAD

**Issue by Edelskjold** [overleaf/overleaf#58]
Hi.

After ive added my Amazon s3 credentials i can no longer run grunt run, without crash.

Without force, im getting following error:
http://pastebin.com/e99BUdbf

Ive tried with grunt run --force which gave this error
http://pastebin.com/yiG9MbqS
please note, duing force webinterface is not available, due to errors (see pastebin)

In config/settings.development.coffee following config is set.

```
    # ShareLaTeX stores binary files like images in S3.
    # Fill in your Amazon S3 credentials below.
    s3:
            key: "MyKEY"
            secret: "MySecret"
            buckets:
                    # The S3 bucket name to store binary files in
                    user_files: "TheBucketName"
```
