### ISSUE TITLE
edit files from somewhere else?

### ISSUE THREAD

**Issue by grauschnabel** [overleaf/overleaf#614]
Hi there,

I would like to know how I could automatically import my tex files generated with R (rstudio) on the same server.  Is there a way just to create a symlink somewher in the data directory, or can i use any api for uploading the new created files from R?  They are in a subfolder of my project and get included when running luatex.

Any hints?

**Comment by das7pad** [comment]
You could try using a bind mount into the container and reference the files via absolute or out of bound relative paths.

```yaml
# docker-compose.yml

# ...
services:
  sharelatex:
    # ...
    volumes:
      # ...
      - /some/local/path:/path/in/container/R
      # or
      - /some/loca/path:/var/lib/sharelatex/data/compiles/R
```

File from the first bind mount would get referenced via `/path/in/container/R/some/file` and files in the second could be referenced via `../R/some/file` from the main document.
I did not check for out of bound read protections, but there are probably none in place.
