### ISSUE TITLE
Nginx Proxy Problems (502 Bad Gateway)

### ISSUE THREAD

**Issue by kromsam** [overleaf/overleaf#707]
## Steps to Reproduce
I installed sharelatex together with the Let's Encrypt docker container. I used the [proposed proxy configuration](https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx) (removed all the duplicates and changed the proxy_pass). Now it looks like this:

```
server {
    listen 443 ssl;

server_name latex.*;

    include /config/nginx/ssl.conf;
    
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains;";

    server_tokens off;

    add_header X-Frame-Options SAMEORIGIN;

    add_header X-Content-Type-Options nosniff;

    client_max_body_size 50M;

    location / {
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_sharelatex sharelatex;
        proxy_pass http://$upstream_sharelatex:4242;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
```

Those are the relevant parts of my docker-compose file:

```
# Let's Encrypt
    letsencrypt:
        container_name: letsencrypt
        image: linuxserver/letsencrypt
        restart: always
        networks:
            - sharelatex_net
            - onlyoffice_net
        environment:
          - PUID=${PUID}
          - PGID=${PGID}
          - TZ=${TZ}
          - URL=${TLD}
          - SUBDOMAINS=${SUBS}
          - VALIDATION=${VAL}
          - EMAIL=${MAILADRES}
        volumes:
          - ${APPDATA}/Letsencrypt:/config
        ports:
          - 443:443
          - 80:80
        cap_add:
          - NET_ADMIN

# Overleaf
    sharelatex:
        container_name: sharelatex
        image: sharelatex/sharelatex
        restart: always
        networks:
            - sharelatex_net
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        links:
            - mongo
            - redis
        privileged: true
        environment:
            - SHARELATEX_APP_NAME=${APPNAME}
            - SHARELATEX_MONGO_URL=${MONGOURL}
            - SHARELATEX_REDIS_HOST=${REDISHOST}
            - REDIS_HOST=${REDISHOST}
            - ENABLED_LINKED_FILE_TYPES=${ENABLEDLINKEDFILETYPES}
            - ENABLE_CONVERSIONS=${ENABLECONVERSIONS}
            - EMAIL_CONFIRMATION_DISABLED=${EMAILCONFIRMATIONDISABLED}
            - SHARELATEX_SITE_URL=${SITEURL}
            - SHARELATEX_NAV_TITLE=${NAVTITLE}
            - SHARELATEX_HEADER_IMAGE_URL=${HEADERIMAGEURL}
            - SHARELATEX_ADMIN_EMAIL=${OVERLEAFMAILADRES}
            - SHARELATEX_LEFT_FOOTER=${LEFTFOOTER}
            - SHARELATEX_RIGHT_FOOTER=${RIGHTFOOTER}
            - SHARELATEX_EMAIL_FROM_ADDRESS=${OVERLEAFMAILADRES}
            - SHARELATEX_EMAIL_SMTP_HOST=${SMTPHOST}
            - SHARELATEX_EMAIL_SMTP_PORT=${SMTPPORT}
            - SHARELATEX_EMAIL_SMTP_SECURE=${SMTPSECURE}
            - SHARELATEX_EMAIL_SMTP_USER=${SMTPUSER}
            - SHARELATEX_EMAIL_SMTP_PASS=${SMTPPASS}
        # - SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH=${SMTPTLSREJECTUNAUTH}
          # - SHARELATEX_EMAIL_SMTP_IGNORE_TLS=${SMTPIGNORETLS}
            - SHARELATEX_CUSTOM_EMAIL_FOOTER=${EMAILFOOTER}
            - SHARELATEX_SECURE_COOKIE=true
            - SHARELATEX_BEHIND_PROXY=true
        volumes:
            - ${APPDATA}/Sharelatex:/var/lib/sharelatex
        ports:
            - 4242:80
    mongo:
        restart: always
        container_name: sharelatex_mongo
        image: mongo
        networks:
            - sharelatex_net
        expose:
            - 27017
        volumes:
            - ${APPDATA}/Sharelatex_DB:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
    redis:
       restart: always
        container_name: sharelatex_redis
        image: redis
        networks:
            - sharelatex_net
        expose:
            - 6379
        volumes:
            - ${APPDATA}/Sharelatex_Redis:/data

networks:
  sharelatex_net:
    driver: bridge
  onlyoffice_net:
    driver: bridge
```

## Expected Behaviour
I hoped that I could just go to latex.domain.tld. But I get a 502 Bad Gateway error.

## Observed Behaviour
The Sharelatex container and the Let's Encrypt container don't give me any errors when I do `docker logs -f`. So my guess is the problem lays in the proxy configuration.
