### ISSUE TITLE
Docker-Compose not working

### ISSUE THREAD

**Issue by SvenC56** [overleaf/overleaf#722]
## Steps to Reproduce

1. Use the `docker-compose.yml`
2. docker-compose up -d

## Expected Behaviour

The Container should be up and running.

## Observed Behaviour

I get infinite loading/ or an empty response if I want to open up example.com:3000/launchpad. It seems that the container is stuck at the `Copying synctex executable to the host` step (see logs at the bottom).

`docker-compose.yml`

<details>

```yml
version: "3.7"

services:
  overleaf:
    container_name: overleaf
    restart: always
    image: sharelatex/sharelatex:2.2.0
    networks:
      - web
      - internal
    ports:
      - 3000:80
    volumes:
      - overleaf_data:/var/lib/sharelatex
    environment:
      SHARELATEX_APP_NAME: Overleaf Community Edition
      SHARELATEX_MONGO_URL: mongodb://overleaf_mongo/sharelatex
      # Same property, unfortunately with different names in
      # different locations
      SHARELATEX_REDIS_HOST: overleaf_redis
      REDIS_HOST: overleaf_redis
      ENABLED_LINKED_FILE_TYPES: "url,project_file"
      # Enables Thumbnail generation using ImageMagick
      ENABLE_CONVERSIONS: "true"
      # Disables email confirmation requirement
      EMAIL_CONFIRMATION_DISABLED: "true"
      # SHARELATEX_BEHIND_PROXY: "true"
      # SHARELATEX_SECURE_COOKIE: "true"
      SHARELATEX_SITE_URL: http://example.com:3000
      SHARELATEX_NAV_TITLE: Overleaf
      # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
      # SHARELATEX_ADMIN_EMAIL: noreply@example.com
      # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
      # SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'
      # SHARELATEX_EMAIL_FROM_ADDRESS: "team@sharelatex.com"
      # SHARELATEX_EMAIL_SMTP_HOST: smtp.mydomain.com
      # SHARELATEX_EMAIL_SMTP_PORT: 587
      # SHARELATEX_EMAIL_SMTP_SECURE: false
      # SHARELATEX_EMAIL_SMTP_USER:
      # SHARELATEX_EMAIL_SMTP_PASS:
      # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
      # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
      # SHARELATEX_CUSTOM_EMAIL_FOOTER: "<div>This system is run by department x </div>"
    depends_on:
      - overleaf_mongo
      - overleaf_redis

  overleaf_mongo:
    restart: always
    image: mongo
    container_name: overleaf_mongo
    networks:
      - internal
    volumes:
      - overleaf_mongo_data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  overleaf_redis:
    restart: always
    image: redis
    container_name: overleaf_redis
    networks:
      - internal
    volumes:
      - overleaf_redis_data:/data

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  overleaf_data:

  overleaf_mongo_data:

  overleaf_redis_data:
```
</details>

Container Logs

<details>

```log
Files: migrations/5_remove_holding_accounts.coffee -> migrations/5_remove_holding_accounts.js


Files: migrations/6_add_track_changes_feature.coffee -> migrations/6_add_track_changes_feature.js


Files: migrations/7_add_token_indexes.coffee -> migrations/7_add_token_indexes.js


Files: migrations/7_add_track_changes_feature_again.coffee -> migrations/7_add_track_changes_feature_again.js


Options: bare, join=false, sourceMap=false, joinExt=".src.coffee", separator="\n"


Reading migrations/1_move_doc_lines_to_doc_collection.coffee...OK


Writing migrations/1_move_doc_lines_to_doc_collection.js...OK


Reading migrations/2_doc_lines_delete_from_project.coffee...OK


Writing migrations/2_doc_lines_delete_from_project.js...OK


Reading migrations/3_pack_docHistory_collection.coffee...OK


Writing migrations/3_pack_docHistory_collection.js...OK


Reading migrations/4_update_user_features.coffee...OK


Writing migrations/4_update_user_features.js...OK


Reading migrations/5_remove_holding_accounts.coffee...OK


Writing migrations/5_remove_holding_accounts.js...OK


Reading migrations/6_add_track_changes_feature.coffee...OK


Writing migrations/6_add_track_changes_feature.js...OK


Reading migrations/7_add_token_indexes.coffee...OK


Writing migrations/7_add_token_indexes.js...OK


Reading migrations/7_add_track_changes_feature_again.coffee...OK


Writing migrations/7_add_track_changes_feature_again.js...OK




Running "shell:migrate" (shell) task


Verifying property shell.migrate exists in config...OK


le: [no files]


Options: stdout, stderr, stdin, failOnError, stdinRawMode=false, preferLocal=false, execOptions={"env":null}


Command: ./node_modules/east/bin/east migrate --adapter east-mongo --url mongodb://overleaf_mongo/sharelatex


target migrations:


	1_move_doc_lines_to_doc_collection


	2_doc_lines_delete_from_project


	3_pack_docHistory_collection


	4_update_user_features


	5_remove_holding_accounts


	6_add_track_changes_feature


	7_add_token_indexes


	7_add_track_changes_feature_again


	9_create_user_emails_array


	10_update_project_tokens


mongodb://overleaf_mongo/sharelatex


migrate `1_move_doc_lines_to_doc_collection`


finding all project id's - Wed Apr 15 2020 10:07:10 GMT+0000 (Coordinated Universal Time)


total found projects in mongo 0 - Wed Apr 15 2020 10:07:10 GMT+0000 (Coordinated Universal Time)


finished


migration done


migrate `2_doc_lines_delete_from_project`


finding all project id's - Wed Apr 15 2020 10:07:10 GMT+0000 (Coordinated Universal Time)


total found projects in mongo 0 - Wed Apr 15 2020 10:07:10 GMT+0000 (Coordinated Universal Time)


finished


migration done


migrate `3_pack_docHistory_collection`


finding all doc id's - Wed Apr 15 2020 10:07:10 GMT+0000 (Coordinated Universal Time)


total found docs in mongo 0 - Wed Apr 15 2020 10:07:10 GMT+0000 (Coordinated Universal Time)


finished at Wed Apr 15 2020 10:07:10 GMT+0000 (Coordinated Universal Time)


migration done


migrate `4_update_user_features`


>> updating all user features:  { '$set':


   { features:


      { collaborators: -1,


        dropbox: true,


        versioning: true,


        references: true,


        templates: true,


        compileTimeout: 180,


        compileGroup: 'standard' } } }


finished updating all user features


migration done


migrate `5_remove_holding_accounts`


[Getting list of holding accounts]


[Got 0 holding accounts]


[FINISHED]


migration done


migrate `6_add_track_changes_feature`


>> enabling trackChanges feature:  { '$set': { 'features.trackChanges': true } }


finished enabling trackChanges feature


migration done


migrate `7_add_token_indexes`


>> Adding indexes for token-based project access: 


>> done adding indexes for token-based project access


migration done


migrate `7_add_track_changes_feature_again`


>> enabling trackChanges feature:  { '$set': { 'features.trackChanges': true } }


finished enabling trackChanges feature


migration done


migrate `9_create_user_emails_array`


updating 0 users


migration done


migrate `10_update_project_tokens`


>> Adding index to projects: {"tokens.readAndWritePrefix":1}, with options: {"unique":true,"partialFilterExpression":{"tokens.readAndWritePrefix":{"$exists":true}},"background":true}


>> Extracting tokens.readAndWritePrefix field for existing projects


>> Updating 0 projects


>> done


migration done




Done, without errors.


All migrations finished


*** Booting runit daemon...


*** Runit started as PID 115


Apr 15 10:07:10 a747a8f38951 cron[129]: (CRON) INFO (pidfile fd = 3)


Apr 15 10:07:10 a747a8f38951 cron[129]: (CRON) INFO (Running @reboot jobs)


>> Copying synctex executable to the host
```
</details>

**Comment by mserranom** [comment]
I just tried running that compose file, removing all `network` sections (running as it is fails due to not existing networks), and works as expected.

Do you have any problem running https://github.com/overleaf/overleaf/blob/master/docker-compose.yml out of the box?

**Comment by SvenC56** [comment]
Hey @mserranom,

oh sorry my bad. I forgot to add the network section. I updated the 1st post accordingly. Could you please retry? I can retry the out of the box compose and give you feedback soon.

Thank you.

```yml
networks:
  web:
    external: true
  internal:
    external: false
```
