### ISSUE TITLE
Problem with volumes when running on windows

### ISSUE THREAD

**Issue by tasptz** [overleaf/overleaf#759]
Currently volumes are mapped to local file paths e.g. 
```
volumes:
    - ~/sharelatex_data:/var/lib/sharelatex
```
Mongo had problems with setting the permissions of the folder and kept restarting.
My suggestion is to use [named volumes](https://docs.docker.com/storage/volumes/), which is encouraged by docker.
It would look like this:
```
version: '2.2'
volumes:
    mongovol:
    redisvol:
    sharelatexvol:
services:
    sharelatex:

...

        volumes:
            - sharelatexvol:/var/lib/sharelatex
```
Docker picks a fitting volume driver and I was able to run the docker service successfully on windows.
