### ISSUE TITLE
502 gateway error for websocket via nginx reverse proxy

### ISSUE THREAD

**Issue by FadedCoder** [overleaf/overleaf#791]
##  Steps to Reproduce
Trying to open a project shows "Unable to connect, please view the connection problems guide to fix the issue." and all websockets give "Error during WebSocket handshake: Unexpected response code: 502"

## Expected Behaviour
Project to load at once

## Observed Behaviour
It will show the error and not load, but after a while it loads automatically (probably not using websockets, cause websockets don't seem to be working)

## Context
Takes a lot of time to open a project.

## Technical Info
docker-compose.yml:
```yml
version: '2.2'
services:
    sharelatex:
        restart: always
        image: sharelatex/sharelatex
        container_name: sharelatex
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        ports:
            - 10100:80
        links:
            - mongo
            - redis
        volumes:
            - $PWD/sharelatex_data:/var/lib/sharelatex
        environment:
            SHARELATEX_APP_NAME: Overleaf
            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
            SHARELATEX_SECURE_COOKIE: 'true'
            SHARELATEX_BEHIND_PROXY: 'true'
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis
            ENABLED_LINKED_FILE_TYPES: 'url,project_file'
            ENABLE_CONVERSIONS: 'true'
            TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var
    mongo:
        restart: always
        image: mongo
        container_name: mongo
        expose:
            - 27017
        volumes:
            - /root/Docker/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5
    redis:
        restart: always
        image: redis:5
        container_name: redis
        expose:
            - 6379
        volumes:
            - /root/Docker/redis_data:/data
```

nginx configuration:
```
server {
    listen 443 ssl;

    ssl_certificate /srv/ssl/cert.pem;
    ssl_certificate_key /srv/ssl/cert.key;
    server_name DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:10100;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'Upgrade';
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 3m;
        proxy_send_timeout 3m;
    }
}
```

## Analysis

Everything works perfectly fine if I directly connect (avoid nginx, type http://&lt;IP&gt;:10100 in browser).
