### ISSUE TITLE
encrypted connection

### ISSUE THREAD

**Issue by 3mrrrx** [overleaf/overleaf#809]
Has any one had any success in hosting overleaf on an encrypted connection? 

One key feature that we currently missing for our use case is the implementation of Let’s Encrypt and secure http within the docker container set up.  The documentation on this topic seems to be vary vague.

Kindly prove us with a simple walk through of the best way to implement this.

**Comment by ocordes** [comment]
Hi, 
ususally for any ssl-connection to any web-app we are using traefik. traefik can get certificates from Let's Encrypt and working perfectly in an own container. Besides the ssl-connection traefik can also perfom load balancing e.g. in docker-compose file with more that one sharelatex container ;-)

**Comment by nobodyinperson** [comment]
Thanks @3mrrrx for bringing this up and @ocordes for the hint on `traefik`.

How **exactly** would one modify the `docker-compose.yml` to include `traefik` so that a simple `docker-compose up` provides a sharelatex service via HTTPS?

The instructions for [NGINX](https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx) completely leave that part out...

**Comment by ocordes** [comment]
okay, I've attached a docker-compose.yml file for traefik. What you need is, a hostname e.g. yourhost.com and an DNS alias *.yourhost.com , so you can use e.g. traefik.yourhost.com or sharelatex.yourhost.com pointing at the same IP without modifying the DNS entries for all names!  You need the port 443 and 80 open for this server!  You can replace XXXX with the hostname you want for the traefik-service e.g. traefik.yourhost.com . You need to create a docker network called web for this. traefik can scan his network for new apps! The YYYY ist a password which protects the traefik web page, you can use htpasswd to create a account. Copy the entry of the htpasswd entry as YYYY. Be careful, you need to replace $ with $$ otherwise the password will not be recognized. 
[traefik-docker-compose.yml.txt](https://github.com/overleaf/overleaf/files/5488256/traefik-docker-compose.yml.txt)

Then in the sharelatex docker-compose.yml you can specify some labels:

labels:
            - "traefik.docker.network=web"
            - "traefik.enable=true"
            - "traefik.http.routers.overleaf.entrypoints=http"
            - "traefik.http.routers.overleaf.rule=(Host(`ZZZZ`)"
            - "traefik.http.middlewares.overleaf-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.overleaf.middlewares=overleaf-https-redirect"
            - "traefik.http.routers.overleaf-secure.entrypoints=https"
            - "traefik.http.routers.overleaf-secure.rule=Host(`ZZZZ`)
            - "traefik.http.routers.overleaf-secure.tls=true"
            - "traefik.http.routers.overleaf-secure.tls.certresolver=http"
            - "traefik.http.routers.overleaf-secure.service=overleaf"
            - "traefik.http.services.overleaf.loadbalancer.server.port=80"
            - "traefik.http.services.overleaf.loadbalancer.sticky.cookie=true"
            - "traefik.http.services.overleaf.loadbalancer.sticky.cookie.name=io"
            - "traefik.http.services.overleaf.loadbalancer.sticky.cookie.httponly=true"
            - "traefik.http.services.overleaf.loadbalancer.sticky.cookie.secure=true"
            - "traefik.http.services.overleaf.loadbalancer.sticky.cookie.samesite=io"

ZZZZ is now the hostname of sharelatex instance, e.g. sharelatex.myhost.com ! You can the docker-compose up as usual :-) and what you can do is scale for the sharelatex (not mongo or redis) instances! 

All information are collected from several tutorials and webpages. Otherwise have a look at the tutorials for traefik !

**Comment by nobodyinperson** [comment]
Thank you very much! We'll try this :smiley:

**Comment by nobodyinperson** [comment]
Thanks again! Sorry for being stupid, but I now have this `docker-compose.yml` file:

```yml
version: '3'

services:
    traefik:
        image: traefik:latest
        container_name: traefik
        restart: unless-stopped
        security_opt:
          - no-new-privileges:true
        networks:
          - web
        ports:
          - 80:80
          - 443:443
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - /var/run/docker.sock:/var/run/docker.sock:ro
          - ./traefik.yml:/traefik.yml:ro
          - ./acme.json:/acme.json
          - ./dynamic_conf.yml:/dynamic_conf.yml
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.traefik.entrypoints=http"
          - "traefik.http.routers.traefik.rule=Host(`traefik.HOST.NAME.DOMAIN.de`)"
          - "traefik.http.middlewares.traefik-auth.basicauth.users=asdf"
          - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
          - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
          - "traefik.http.routers.traefik-secure.entrypoints=https"
          - "traefik.http.routers.traefik-secure.rule=Host(`traefik.HOST.NAME.DOMAIN.de`)"
          - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
          - "traefik.http.routers.traefik-secure.tls=true"
          - "traefik.http.routers.traefik-secure.tls.certresolver=http"
          - "traefik.http.routers.traefik-secure.service=api@internal"
    sharelatex:
        restart: always
        # Server Pro users:
        # image: quay.io/sharelatex/sharelatex-pro
        image: sharelatex/sharelatex
        container_name: sharelatex
        networks:
          - web
        depends_on:
            mongo:
                condition: service_healthy
            redis:
                condition: service_started
        ports:
            - 80:80
        links:
            - mongo
            - redis
        volumes:
            - ~/sharelatex_data:/var/lib/sharelatex
            ########################################################################
            ####  Server Pro: Un-comment the following line to mount the docker ####
            ####             socket, required for Sibling Containers to work    ####
            ########################################################################
            # - /var/run/docker.sock:/var/run/docker.sock
        environment:

            SHARELATEX_APP_NAME: Overleaf Community Edition

            SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex

            # Same property, unfortunately with different names in
            # different locations
            SHARELATEX_REDIS_HOST: redis
            REDIS_HOST: redis

            ENABLED_LINKED_FILE_TYPES: 'url,project_file'

            # Enables Thumbnail generation using ImageMagick
            ENABLE_CONVERSIONS: 'true'

            # Disables email confirmation requirement
            EMAIL_CONFIRMATION_DISABLED: 'true'

            # temporary fix for LuaLaTex compiles
            # see https://github.com/overleaf/overleaf/issues/695
            TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

            ## Set for SSL via nginx-proxy
            #VIRTUAL_HOST: 103.112.212.22
            SHARELATEX_SECURE_COOKIE: 'true'
            SHARELATEX_BEHIND_PROXY: 'true'

            # SHARELATEX_SITE_URL: http://sharelatex.mydomain.com
            # SHARELATEX_NAV_TITLE: Our ShareLaTeX Instance
            # SHARELATEX_HEADER_IMAGE_URL: http://somewhere.com/mylogo.png
            # SHARELATEX_ADMIN_EMAIL: support@it.com

            # SHARELATEX_LEFT_FOOTER: '[{"text": "Powered by <a href=\"https://www.sharelatex.com\">ShareLaTeX</a> 2016"},{"text": "Another page I want to link to can be found <a href=\"here\">here</a>"} ]'
            # SHARELATEX_RIGHT_FOOTER: '[{"text": "Hello I am on the Right"} ]'

            # SHARELATEX_EMAIL_FROM_ADDRESS: "team@sharelatex.com"

            # SHARELATEX_EMAIL_AWS_SES_ACCESS_KEY_ID:
            # SHARELATEX_EMAIL_AWS_SES_SECRET_KEY:

            # SHARELATEX_EMAIL_SMTP_HOST: smtp.mydomain.com
            # SHARELATEX_EMAIL_SMTP_PORT: 587
            # SHARELATEX_EMAIL_SMTP_SECURE: false
            # SHARELATEX_EMAIL_SMTP_USER:
            # SHARELATEX_EMAIL_SMTP_PASS:
            # SHARELATEX_EMAIL_SMTP_TLS_REJECT_UNAUTH: true
            # SHARELATEX_EMAIL_SMTP_IGNORE_TLS: false
            # SHARELATEX_CUSTOM_EMAIL_FOOTER: "This system is run by department x"

            ################
            ## Server Pro ##
            ################

            # SANDBOXED_COMPILES: 'true'

            # SANDBOXED_COMPILES_SIBLING_CONTAINERS: 'true'
            # SANDBOXED_COMPILES_HOST_DIR: '/var/sharelatex_data/data/compiles'
            # SYNCTEX_BIN_HOST_PATH: '/var/sharelatex_data/bin/synctex'

            # DOCKER_RUNNER: 'false'

            ## Works with test LDAP server shown at bottom of docker compose
            # SHARELATEX_LDAP_URL: 'ldap://ldap:389'
            # SHARELATEX_LDAP_SEARCH_BASE: 'ou=people,dc=planetexpress,dc=com'
            # SHARELATEX_LDAP_SEARCH_FILTER: '(uid={{username}})'
            # SHARELATEX_LDAP_BIND_DN: 'cn=admin,dc=planetexpress,dc=com'
            # SHARELATEX_LDAP_BIND_CREDENTIALS: 'GoodNewsEveryone'
            # SHARELATEX_LDAP_EMAIL_ATT: 'mail'
            # SHARELATEX_LDAP_NAME_ATT: 'cn'
            # SHARELATEX_LDAP_LAST_NAME_ATT: 'sn'
            # SHARELATEX_LDAP_UPDATE_USER_DETAILS_ON_LOGIN: 'true'

            # SHARELATEX_TEMPLATES_USER_ID: "578773160210479700917ee5"
            # SHARELATEX_NEW_PROJECT_TEMPLATE_LINKS: '[ {"name":"All Templates","url":"/templates/all"}]'


            # SHARELATEX_PROXY_LEARN: "true"

    mongo:
        restart: always
        image: mongo
        container_name: mongo
        networks:
          - web
        expose:
            - 27017
        volumes:
            - ~/mongo_data:/data/db
        healthcheck:
            test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
            interval: 10s
            timeout: 10s
            retries: 5

    redis:
        restart: always
        image: redis:5
        networks:
          - web
        container_name: redis
        expose:
            - 6379
        volumes:
            - ~/redis_data:/data

    # ldap:
    #    restart: always
    #    image: rroemhild/test-openldap
    #    container_name: ldap
    #    expose:
    #        - 389

    # See https://github.com/jwilder/nginx-proxy for documentation on how to configure the nginx-proxy container,
    # and https://github.com/overleaf/overleaf/wiki/HTTPS-reverse-proxy-using-Nginx for an example of some recommended
    # settings. We recommend using a properly managed nginx instance outside of the Overleaf Server Pro setup,
    # but the example here can be used if you'd prefer to run everything with docker-compose

    # nginx-proxy:
    #     image: jwilder/nginx-proxy
    #     container_name: nginx-proxy
    #     ports:
    #       #- "80:80"
    #       - "443:443"
    #     volumes:
    #       - /var/run/docker.sock:/tmp/docker.sock:ro
    #       - /home/sharelatex/tmp:/etc/nginx/certs

networks:
  web:
    external: true
```

I created a `web` network with `sudo docker network create web`.

A `docker-compose up` keeps either giving me errors that a `0.0.0.0:80` is already allocated (`sharelatex`) or it starts fine but I still can only access it via HTTP (port 80), not HTTPS.

The machine I'm running it on gets a dynamic DNS name (`hostname.subdomain.domain.de`) based on its hostname. I don't know if another subdomain works with this?

What would be the **simplest** `docker-compose.yml` configuration if I even don't care about using a specific subdomain for the Overleaf instance? I just want to be able to get to the Overleaf instance by pointing to `https://hostname.subdomain.domain.de`.

Any help is much appreciated!
